using System;
using static PayrollSystem.UsefullUniversalCommands;

namespace PayrollSystem
{
    public class User
    {
        private string _username, _password, _email;
        private int _employeeID;
        private int _privliage;

        public User() //Default constructor
        {
            Privliage = 0; //starts off as 0
            Username = "DefaultUser";
            Password = "password123";
            ID = GenerateRandomNumber(9999999); //User ID should be a random number generated when creating a new employee, and not equal to any other existing User ID.
            AutoGeneratedEmail();
        }
        public User(string username) : this()
        {
            Username = username;
            AutoGeneratedEmail();
        }

        public User(string username, string password) : this(username)
        {
            Password = password;
            AutoGeneratedEmail();
        }

        public User(string username, string password, string email) : this(username, password)
        {
            Email = email;
        }

        private string AutoGeneratedEmail() //only for use in constructors so far
        {
            return $"{ID}@company.com"; //make it company name from application perhaps?
        }


        public int Privliage
        {
            get { return _privliage; }
            set { _privliage = value; }
        }

        public string Email
        {
            get { return _email; }
            set { _email = value; }
        }

        public string Username
        {
            get { return _username; }
            set { _username = value; }
        }

        public string Password
        {
            get { return _password; }
            set { _password = value; }
        }

        public int ID
        {
            get { return _employeeID; }
            set { _employeeID = value; }
        }

        public string ReturnUserInfoAsString()
        {
            Console.WriteLine("Displaying user info:");
            return $"Employee ID: {_employeeID}\n" +
                   $"Username: {_username}\n" +
                   $"Password: {_password}\n" +
                   $"Email: {_email}";
        }
    }
}


//[PREFERABLY]: $"{_FirstName}+{new Random().Next(999)}"; //Generates a username based on first name and a random 3 digit number. Add a check to ensure there is no other username